name: flutter_broadcasts
description: A plugin for sending and receiving broadcasts with Android intents and iOS notifications.
version: 0.5.1
repository: https://github.com/kevlatus/flutter_broadcasts

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.35.5"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: de.kevlatus.flutter_broadcasts
        pluginClass: FlutterBroadcastsPlugin
      ios:
        pluginClass: FlutterBroadcastsPlugin
